"""
Snapshot the Fund II portfolio from the data room into fund2-data.js.

Reads ../investor-data-room/index.html and emits a self-contained JS file
exposing window.FUND2_DEALS. Joins each Fund II position with the data
room's RAW row to attach `irr` (proj. IRR) and `type` (financing structure),
which aren't carried in the Borrowing-Base-Tape-derived FUND2_DEALS block.

Re-run after the data room refreshes its tape:
  py build_fund2_data.py

Output: fund2-data.js (overwritten in place).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA_ROOM = HERE.parent / "investor-data-room" / "index.html"
OUT = HERE / "fund2-data.js"


def extract_fund2_block(src: str) -> list[dict]:
    m = re.search(
        r"/\*\s*@fund2-data-start\s*\*/.*?const\s+FUND2_DEALS\s*=\s*(\[.*?\]);.*?/\*\s*@fund2-data-end\s*\*/",
        src,
        re.DOTALL,
    )
    if not m:
        raise SystemExit("Could not find @fund2-data sentinel block in the data room.")
    return json.loads(m.group(1))


def extract_raw_index(src: str) -> dict[str, dict]:
    """Parse the RAW = [...] array. Each row is a single-line JS object literal
    with unquoted keys, so we convert keys to JSON form before json.loads."""
    m = re.search(r"const\s+RAW\s*=\s*\[(.*?)\n\];", src, re.DOTALL)
    if not m:
        raise SystemExit("Could not find const RAW = [...] in the data room.")
    body = m.group(1)
    rows: dict[str, dict] = {}
    row_pat = re.compile(r"\{[^{}]*\}")
    key_pat = re.compile(r"([{,]\s*)([A-Za-z_][A-Za-z0-9_]*)\s*:")
    for raw_obj in row_pat.findall(body):
        json_obj = key_pat.sub(r'\1"\2":', raw_obj)
        try:
            row = json.loads(json_obj)
        except json.JSONDecodeError:
            continue
        rid = str(row.get("id", "")).strip()
        if rid:
            rows[rid] = row
    return rows


def merge(fund2: list[dict], raw_by_id: dict[str, dict]) -> list[dict]:
    merged: list[dict] = []
    for f in fund2:
        fid = str(f.get("id", "")).strip()
        r = raw_by_id.get(fid, {})
        fund_date = f.get("fund_date") or ""
        vintage = None
        if len(fund_date) >= 4 and fund_date[:4].isdigit():
            vintage = int(fund_date[:4])
        exposure = f.get("exposure_pct")
        slice_factor = (exposure / 100.0) if isinstance(exposure, (int, float)) else None
        raw_advance = r.get("advance")
        raw_collected = r.get("collected")
        fund_advance = (
            raw_advance * slice_factor
            if isinstance(raw_advance, (int, float)) and slice_factor is not None
            else None
        )
        fund_collected = (
            raw_collected * slice_factor
            if isinstance(raw_collected, (int, float)) and slice_factor is not None
            else None
        )
        merged.append(
            {
                "id": fid,
                "name": f.get("name") or f"Deal {fid}",
                "asset": f.get("asset") or r.get("asset") or "",
                "type": r.get("type") or "",
                "vintage": vintage,
                "exposure_pct": exposure,
                "fund_advance": fund_advance,
                "fund_collected": fund_collected,
                "fund_outstanding": f.get("fund_outstanding"),
                "fund_monthly_pmt": f.get("fund_monthly_pmt"),
                "ltv": f.get("ltv"),
                "dscr": f.get("dscr"),
                "irr": r.get("irr"),
                "term_months": f.get("term_months"),
                "fund_date": fund_date,
                "term_end": f.get("term_end") or "",
                "status": f.get("status") or "",
                "city_state": f.get("city_state") or "",
                "units": f.get("units"),
                "one_pager": f.get("one_pager") or "",
            }
        )
    return merged


def main() -> None:
    src = DATA_ROOM.read_text(encoding="utf-8")
    fund2 = extract_fund2_block(src)
    raw_by_id = extract_raw_index(src)
    merged = merge(fund2, raw_by_id)

    missing_meta = [d["id"] for d in merged if not d["type"] or d["irr"] is None]
    payload = json.dumps(merged, indent=2, ensure_ascii=False)

    header = (
        "// Auto-generated by build_fund2_data.py from ../investor-data-room/index.html.\n"
        f"// {len(merged)} Fund II positions; do not hand-edit.\n"
        f"// Positions missing irr/type lookup in RAW: {len(missing_meta)}\n"
    )
    OUT.write_text(f"{header}window.FUND2_DEALS = {payload};\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(merged)} positions; {len(missing_meta)} missing portfolio metadata).")


if __name__ == "__main__":
    main()
